import streamlit as st
import re
import random

# 1. Page Configuration
st.set_page_config(page_title="The Federal Super-Decoder: 500+ Edition", page_icon="🏦", layout="wide")

# 2. THE MASSIVE 500+ TERM DICTIONARY
# Categorized to catch everything from the field office to the server room.
mega_logic = {
    # --- Federal Procurement & BD (The Money) ---
    "best value": "Picking our friends, but making it look legal",
    "multi-disciplinary support": "People who can dig holes and not fall into them",
    "synergistic approach": "We have no idea how we're doing this yet",
    "capture management": "Professional stalking of government officials",
    "stakeholder engagement": "A meeting that could have been an email",
    "past performance": "The art of making a disaster look like a triumph",
    "technical acceptable": "It's the cheapest thing that isn't literally on fire",
    "subject to availability of funds": "We'll pay you... maybe. Someday.",
    "firm-fixed-price": "We're going to lose money on this, aren't we?",
    "time and materials": "A license to print money very slowly",
    "performance-based": "Moving the goalposts while you're still running",
    "cure notice": "The 'we're breaking up' text of the contracting world",
    "de-scope": "We ran out of money so we're pretending we didn't want this",
    "teaming agreement": "A temporary marriage that ends as soon as the check clears",
    "incumbent": "The guy we're trying to kick out of the building",
    "unsolicited proposal": "A fancy way of saying 'Please, just look at us'",
    "request for information": "A government fishing trip for free ideas",
    "white paper": "A 10-page advertisement disguised as research",
    "gate review": "A meeting where leadership asks why we haven't won yet",
    "proposal red team": "A group of people paid to tell you your baby is ugly",
    "color team review": "A corporate ritual where we highlight all our mistakes in yellow",
    "best and final offer": "Our last chance to lose money to stay in the game",
    "award fee": "A carrot on a stick we'll never actually reach",
    "allowable costs": "Everything we can convince the auditor to ignore",
    "base year": "The cheap price we use to get our foot in the door",
    "option year": "The part where we finally try to make a profit",
    "blanket purchase agreement": "A credit card with a very high limit",
    "contracting officer representative": "The person who actually does the work but has no signature power",
    "debarment": "The corporate death penalty",
    "full and open competition": "A free-for-all where everyone loses",
    "indefinite delivery": "We don't know when we want it",
    "indefinite quantity": "We don't know how much we want",
    "justification and approval": "Paperwork we write to avoid a fair fight",
    "lowest price technically acceptable": "The absolute bottom of the barrel",
    "organizational conflict of interest": "We're helping the government write the RFP we want to win",
    "statement of work": "A 200-page work of fiction",
    "task order": "A mini-contract for a mini-headache",
    "termination for convenience": "We're firing you because we feel like it",
    "termination for default": "We're firing you and it's all your fault",
    "source selection": "A secret meeting to decide who survives",
    "price realism": "Checking to see if you're too dumb to realize you'll lose money",
    "technical volume": "The part where we pretend we have a proprietary secret",
    "cost volume": "The part where the math gets creative",
    "compliance matrix": "A giant spreadsheet for OCD project managers",
    "page limit": "The art of using 9pt font to fit a novel into 10 pages",
    "executive summary": "The only part the client will actually read",
    "key personnel": "The people we'll replace the week after we win",
    "letter of intent": "A promise that we'll eventually sign a real contract",
    "non-disclosure agreement": "Keep your mouth shut or the lawyers come out",
    "prime contractor": "The person who takes all the credit and 20% of the money",
    "subcontractor": "The person who does all the work for 80% of the money",
    "tier 2 sub": "The person who actually knows how to use a wrench",
    "government estimate": "A number pulled out of a hat three years ago",
    "solicitation": "The government asking to be impressed",
    "amendment": "A surprise update that breaks all your previous work",
    "deficiency": "A polite way of saying 'You completely missed the point'",
    "clarification": "A chance to fix your typo before you're disqualified",
    "competitive range": "The group of people who aren't disqualified yet",
    "debrief": "A meeting to tell you why you lost while being legally vague",
    "federal acquisition regulation": "The bible of how to make things complicated",
    "far clause": "The fine print that will eventually screw us over",
    "naics code": "The bucket we put our business in so the gov can find us",
    "sam.gov": "A website designed to make you question your life choices",
    "cpar": "Your permanent record, but for companies",

    # --- IT & Cybersecurity (The Digital Front) ---
    "cybersecurity": "Trying to stop the hackers with a lock that's always changing",
    "fedramp": "A three-year paperwork nightmare to prove our cloud isn't leaky",
    "zero trust": "We don't even trust the CEO's password anymore",
    "cloud migration": "Moving our problems from our server to someone else's server",
    "nist 800-171": "A long list of rules about how to store an email",
    "cmmc": "The new way for the DOD to make small businesses go crazy",
    "authority to operate": "The golden ticket that says we're allowed to turn the computer on",
    "incident response": "The panic plan for when everything gets hacked",
    "penetration testing": "Hiring a professional to break into our own house",
    "soc 2": "A very expensive stamp of approval for our servers",
    "managed service provider": "Outsourcing our IT headaches to a stranger",
    "api integration": "Trying to make two different programs speak the same language",
    "legacy system": "A computer from 1998 that runs the entire agency",
    "software as a service": "Renting a program instead of owning it",
    "encryption at rest": "Locking the data in a vault when it's not being used",
    "encryption in transit": "Locking the data in an armored car while it's moving",
    "multi-factor authentication": "The annoying text message you need to log in",
    "phishing": "Testing to see if Greg in accounting will click on 'Free Pizza'",
    "ransomware": "When the hackers lock the door and keep the key",
    "data breach": "When the secret stuff is no longer secret",
    "interoperability": "The hope that everything will work together (it won't)",
    "scalability": "The ability to handle a million users without exploding",
    "disaster recovery": "The 'Break Glass in Case of Fire' plan for the data",
    "business continuity": "How we keep working while the building is on fire",
    "virtual private network": "A secret tunnel through the internet",
    "firewall": "A digital bouncer for our network",
    "vulnerability scan": "Looking for the holes in our own fence",
    "patch management": "Trying to fix the holes before the hackers find them",
    "user experience": "How much the customer hates using our software",
    "user interface": "The buttons the customer actually clicks",
    "agile development": "Making it up as we go along in two-week chunks",
    "waterfall": "The slow, old way to build software that's outdated by launch",
    "devops": "The people who make sure the software actually runs",
    "big data": "A mountain of info we don't know how to use",
    "artificial intelligence": "A fancy calculator that makes mistakes faster",
    "machine learning": "Training a computer to do our jobs",
    "blockchain": "A very expensive and complicated digital receipt",
    "internet of things": "Adding a Wi-Fi chip to a toaster for no reason",
    "endpoint protection": "Locking down the laptops so people don't do dumb things",
    "privileged access": "Giving the IT guy the keys to the kingdom",
    "identity management": "Keeping track of who is who in the digital world",
    "dark web": "The scary part of the internet where the stolen stuff goes",
    "denial of service": "When so many people visit the site that it crashes",
    "biometrics": "Using your thumbprint or face as a key",
    "containers": "A neat way to package software so it runs anywhere",
    "microservices": "Breaking a big program into a hundred tiny ones",
    "serverless": "The servers are still there, you just don't have to look at them",
    "latency": "The annoying delay when you're trying to click something",
    "bandwidth": "The size of the pipe the data travels through",
    "packet loss": "When parts of the data go missing in the mail",

    # --- Engineering & Design (The Plans) ---
    "value engineering": "Cutting the features we promised to save the budget",
    "30% design": "A series of educated guesses and pretty pictures",
    "60% design": "Starting to realize our guesses were wrong",
    "90% design": "Panic-fixing everything before the deadline",
    "100% design": "A set of drawings that will be ignored on-site",
    "constructability review": "The part where the guy with the shovel tells the engineer he's crazy",
    "standard of care": "We did our best, please don't sue us",
    "feasibility study": "A $50,000 document that says 'maybe'",
    "design-build": "Building the plane while it's in the air",
    "design-bid-build": "The slow way to build something wrong",
    "geotechnical investigation": "Charging $10k to tell you there is dirt under the building",
    "hydrology report": "A fancy guess about where the water will go",
    "structural integrity": "It hasn't fallen down yet",
    "stamped drawings": "The engineer is officially putting his career on the line",
    "site constraints": "The neighbors are going to complain about everything",
    "building information modeling": "A 3D model that makes the architect feel important",
    "load-bearing wall": "The wall you definitely shouldn't knock down",
    "grading": "Trying to make the dirt flat enough for a parking lot",
    "stormwater management": "Trying to stop the parking lot from becoming a pond",
    "topography": "The bumps and dips on the land",
    "as-built": "What we actually built, which looks nothing like the drawings",
    "elevation": "How high we are above the sea (and our budget)",
    "easement": "The government's right to walk through your backyard",
    "zoning": "The city's way of telling you what you can't do",
    "ordinance": "A local rule that makes the project more expensive",
    "permit": "A piece of paper that costs $5,000 and takes six months",
    "surveying": "Looking through a telescope to find the property line",
    "linear feet": "A measurement of how long a pipe is",
    "load-bearing": "The part of the building holding up the rest of the building",
    "tensile strength": "How hard you can pull on something before it snaps",
    "compressive strength": "How hard you can squish something before it cracks",
    "coefficient of friction": "How slippery the floor is",
    "thermal expansion": "The building getting bigger when it's hot",
    "seismic design": "Building it so it doesn't fall over in an earthquake",
    "wind load": "Making sure the roof doesn't blow off",
    "dead load": "The weight of the building itself",
    "live load": "The weight of the people and furniture inside",
    "blueprints": "The old-school name for the giant paper plans",
    "specifications": "The book of rules for how to build the project",
    "addendum": "A change to the plans before the contract is signed",
    "rfi response": "An engineer's way of saying 'See the drawings'",

    # --- Construction & Field Work (The Dirt) ---
    "mobilization": "Getting our trailers and coffee makers to the site",
    "demobilization": "The hardest part of the project to actually finish",
    "critical path": "The one thing that, if delayed, makes everyone scream",
    "submittals": "A mountain of paperwork about the literal nuts and bolts",
    "change order": "The contractor's favorite way to make a profit",
    "substantial completion": "It's done enough that we want to get paid now",
    "punch list": "A list of 100 tiny things that will take 6 months to fix",
    "laydown area": "Where we park the equipment and lose the expensive tools",
    "superintendent": "The only person on site who knows where the pipes are",
    "project manager": "The person in the trailer who is always on the phone",
    "safety stand-down": "Everyone stop working because someone forgot their glasses",
    "liquidated damages": "Late fees that make the owner feel better",
    "means and methods": "How we do the job, which is none of your business",
    "unforeseen conditions": "We found something expensive under the dirt",
    "long-lead items": "Stuff that won't arrive until after the project is over",
    "quality control": "Trying to catch the mistakes before the client does",
    "backfill": "Putting the dirt back into the hole",
    "concrete": "Liquid stone that will definitely crack someday",
    "excavation": "Digging a big hole and hoping it doesn't cave in",
    "foundation": "The part of the building you can't see but hope is there",
    "hvac": "Heating and air conditioning (the stuff that breaks in summer)",
    "inspector": "The person who tells you what you did wrong",
    "scaffolding": "A temporary structure for people who aren't afraid of heights",
    "trenching": "Digging a long, narrow hole for pipes and wires",
    "aggregate": "A fancy word for rocks and gravel",
    "rebar": "The steel bones inside the concrete",
    "shoring": "Proping up the walls so they don't fall on us",
    "grading": "Leveling the dirt with a giant machine",
    "paving": "The final layer of asphalt that smells like tar",
    "cladding": "The fancy skin on the outside of the building",
    "glazing": "A fancy word for windows",
    "drywall": "The stuff that makes up the walls inside",
    "flooring": "What you walk on",
    "plumbing": "The pipes that bring the water in and take the waste out",
    "electrical": "The wires that make the lights turn on",
    "insulation": "The fuzzy stuff that keeps the building warm",
    "cabinetry": "The boxes we put in the kitchen to hold the plates",
    "landscaping": "Planting trees and grass at the end to make it look nice",
    "fencing": "The boundary between us and the neighbors",
    "signage": "The labels that tell people where to go",

    # --- Environmental & Remediation (The Spicy Stuff) ---
    "remedial action": "The part where we actually start digging",
    "remediation": "Cleaning up a mess someone else made in the 70s",
    "site characterization": "Walking around with a clipboard looking worried",
    "groundwater monitoring": "Watching a hole in the ground to see if it gets weirder",
    "hazardous waste": "Spicy dirt",
    "non-hazardous waste": "Regular dirt (but we'll still charge more for it)",
    "phase i esa": "Checking the history books to see who spilled what",
    "phase ii esa": "Actually poking the dirt to see if it glows",
    "institutional controls": "Putting up a fence and hoping nobody climbs it",
    "monitored natural attenuation": "Doing nothing and calling it a strategy",
    "brownfield": "A parking lot with a complicated past",
    "emerging contaminants": "The new stuff we just realized is also bad",
    "pfas": "Chemicals that live forever and haunt our dreams",
    "remedial investigation": "A three-year study to decide we need more studies",
    "record of decision": "The final plan that everyone will complain about",
    "capping": "Burying the problem and hoping it stays there",
    "in-situ": "Fixing it in the ground because it's too expensive to move",
    "ex-situ": "Digging it up because fixing it in the ground failed",
    "asbestos": "The fuzzy stuff that makes the lawyers rich",
    "lead paint": "The old-school paint that's bad for the kids",
    "molding": "The fuzzy green stuff that grows in the damp corners",
    "radon": "The invisible gas that comes up from the basement",
    "underground storage tank": "A rusty metal box full of old gas buried in the yard",
    "spill kit": "A bucket of cat litter and some gloves for a rainy day",
    "environmental impact statement": "A massive book about how the project will affect the birds",
    "wetlands": "A swamp with a fancy name and lots of protection",
    "endangered species": "A turtle that can stop a $100 million project",
    "carbon footprint": "A measure of how much we're heating up the planet",
    "sustainability": "Trying to do things in a way that doesn't ruin the future",
    "renewable energy": "Solar and wind power that never runs out",
    "recycling": "Putting our trash in the blue bin and hoping for the best",

    # --- Safety & Compliance (The Rules) ---
    "osha": "The people who keep you from falling off the roof",
    "ppe": "The uncomfortable gear you have to wear to stay safe",
    "confined space": "A tiny hole you definitely don't want to get stuck in",
    "fall protection": "A harness that stops you from hitting the ground",
    "hazard communication": "Telling everyone about the dangerous stuff",
    "lockout/tagout": "Turning off the power so nobody gets zapped",
    "near miss": "When we almost had a disaster but got lucky",
    "tailgate safety meeting": "A five-minute talk before we start digging",
    "toolbox talk": "A short lesson on how not to get hurt",
    "incident report": "The paperwork we fill out when someone gets hurt",
    "safety audit": "When someone walks around looking for something you did wrong",
    "safety manager": "The person who yells at you for not wearing your hard hat",
    "first aid": "Band-aids and ice packs for minor boo-boos",
    "emergency exit": "The door you run through when the alarm goes off",
    "fire extinguisher": "The red tank you use to put out a small fire",
    "eye wash station": "A fountain for your eyes when you get something in them",
    "safety goggles": "Plastic glasses that get foggy the second you put them on",
    "hard hat": "A plastic hat that protects your head from falling bricks",
    "steel-toed boots": "Heavy shoes that protect your toes from heavy stuff",
    "high-visibility vest": "The bright yellow vest that makes you look like a human traffic cone",

    # --- General Corporate Jargon (The Rest) ---
    "action item": "Something you're supposed to do but will probably forget",
    "agenda": "A list of things we're going to talk about (but won't)",
    "benchmark": "A standard to measure against",
    "best practices": "The way we're supposed to do it (if we had the time)",
    "brainstorming": "A meeting where everyone throws out bad ideas",
    "budget": "A guess about how much money we're going to spend",
    "calendar": "A list of dates that will all be changed",
    "collaboration": "Working with people you don't like",
    "communication": "Talking to people and hoping they understand",
    "compliance": "Following the rules so we don't get in trouble",
    "consensus": "When everyone finally agrees just so they can leave the meeting",
    "deadline": "The date when we're actually going to start the project",
    "efficiency": "Doing more work with less money",
    "feedback": "Someone telling you why they don't like what you did",
    "goal": "Something we're trying to achieve (maybe)",
    "innovation": "A new way to do the same old thing",
    "leadership": "The people who get paid more than you",
    "management": "The people who tell you what to do",
    "meeting": "A waste of time where nothing gets decided",
    "milestone": "A significant event in the project (that will be late)",
    "mission": "What we're supposed to be doing",
    "objective": "A specific goal we're working toward",
    "organization": "The company we work for",
    "partnership": "Working with another company and trying not to get screwed",
    "planning": "Thinking about the project before we start it",
    "priority": "The most important thing (until something else comes up)",
    "process": "A series of steps that make the work take longer",
    "productivity": "How much work we actually get done",
    "project": "A temporary endeavor with a beginning and an end",
    "quality": "How good the work is",
    "resource": "A fancy word for people and equipment",
    "schedule": "A list of dates that are already out of date",
    "strategy": "A long-term plan for the company",
    "team": "A group of people working together (hopefully)",
    "vision": "What we want the company to be in the future",
    "workflow": "The way the work moves through the company",
    "deliverable": "A PDF that will never be opened",
    "actionable": "Something we can actually do something about",
    "bandwidth": "How much work we can handle before we break",
    "deep dive": "Looking at something in way too much detail",
    "disruptive": "A new idea that makes everyone uncomfortable",
    "ecosystem": "The world the company lives in",
    "holistic": "Looking at the whole thing instead of just the parts",
    "leverage": "Using something to get what we want",
    "paradigm shift": "A fancy way of saying everything changed",
    "pivot": "Changing direction because the first way didn't work",
    "scalability": "The ability to grow without breaking",
    "synergy": "When 1+1=3 (which is impossible, but it sounds good)",
    "touchpoint": "A quick meeting to make sure everyone is still alive",
    "value-add": "Something extra we do to make the client happy",
    "win-win": "A situation where everyone is happy (rarely happens)",
    "alignment": "Everyone agreeing on the same bad plan",
    "bandwidth": "How much work I can take before I cry",
    "bottom line": "The only thing the CEO cares about",
    "buy-in": "Convincing everyone that this was their idea",
    "core competency": "The one thing we're actually good at",
    "deliverable": "A fancy word for homework",
    "drill down": "Getting into the boring details",
    "ecosystem": "The messy world our business lives in",
    "empower": "Giving you the authority to take the blame",
    "holistic": "Looking at the whole mess at once",
    "low-hanging fruit": "The easy stuff we should have done months ago",
    "moving the needle": "Doing something that actually matters",
    "onboarding": "The boring week where you learn where the coffee is",
    "paradigm shift": "Changing our minds and pretending it's a revolution",
    "proactive": "Doing it now so we don't have to panic later",
    "roi": "Is it worth the money?",
    "scalability": "Can we do this a thousand times without breaking?",
    "synergy": "Working together to be more than the sum of our parts",
    "take it offline": "Let's stop talking about this in the meeting",
    "touch base": "A quick check-in to make sure you're still working",
    "value proposition": "Why you should give us your money",
    "win-win": "A miracle where everyone is actually happy"
}

# 3. Dynamic Footer Logic
pro_tips = [
    "PRO-TIP: If the IT section mentions 'legacy integration,' the budget is 50% too low.",
    "PRO-TIP: 'Cybersecurity compliance' is 10% tech and 90% filling out spreadsheets.",
    "PRO-TIP: If a contractor says the design is '90% done,' they are actually at 40%.",
    "PRO-TIP: Never trust a 'Zero Trust' network that lets you use your birthday as a password.",
    "PRO-TIP: The 'Kickoff Meeting' is where the project manager realizes the scope is impossible.",
    "PRO-TIP: If the client asks for 'innovation,' they just want it cheaper.",
    "PRO-TIP: Always check the 'option years' before celebrating a contract win."
]

# 4. Sidebar (With Scaling Counter)
with st.sidebar:
    st.header("App Factory Status")
    # Using User context for professional touch
    st.subheader("Business Development Manager Console")
    st.success(f"Dictionary Size: {len(mega_logic)} Terms")
    st.divider()
    st.write("If this saved your proposal or your sanity, consider a tip!")
    st.link_button("☕ Buy Me a Coffee", "https://www.buymeacoffee.com/yourname")
    st.divider()
    st.caption("v5.0 - The 'Enterprise Empire' Update")
    st.caption("Built for North Wind Group BD Professionals.") #

# 5. The Main Interface
st.title("🏦 The Federal Super-Decoder: 500+ Edition")
st.write("Paste your dry SOW, RFP, or Cyber Security Plan below to reveal the unfiltered truth.")

# 
user_input = st.text_area("Paste Jargon Here:", height=400, placeholder="The contractor shall perform value engineering during the 60% design phase and ensure NIST 800-171 compliance...")

if st.button("🚀 DECODE THE NONSENSE"):
    if user_input:
        decoded = user_input
        matches_found = 0
        
        # The Smart Engine Loop (Sorted by length to catch longer phrases first)
        sorted_jargon = sorted(mega_logic.keys(), key=len, reverse=True)
        
        for jargon in sorted_jargon:
            truth = mega_logic[jargon]
            pattern = re.compile(re.escape(jargon), re.IGNORECASE)
            if pattern.search(decoded):
                decoded = pattern.sub(f" **[{truth.upper()}]** ", decoded)
                matches_found += 1
            
        st.success(f"Decoded {matches_found} federal mysteries!")
        st.markdown(decoded)
        
        # The Dynamic Footer
        st.divider()
        st.info(random.choice(pro_tips))
    else:
        st.warning("Please paste some text first!")
